### PR TITLE
Added a notebook.

### PR DESCRIPTION
**Pull request by nguy**
Added a notebook that pulls down the latest NEXRAD for a given ID, plots, and then opens in ARTView.

### CODE REVIEW

**Comment by scollis** [comment]
Thanks Nick!

**Comment by nguy** [comment]
You bet, another question to the mailing list. Thinking this may be the
best way to talk about ARTView. Instead of a powerpoint, the participants
could just run this and mess around with the interface.
The other possibility is to have a small set of data files that they could
open.

**Comment by scollis** [comment]
Yep!
We will have thumbdrives (16GB) so no issues with files.. I will also be 
setting up a figshare repo

On 9/4/15 10:48 AM, Nick wrote:

> You bet, another question to the mailing list. Thinking this may be the
> best way to talk about ARTView. Instead of a powerpoint, the participants
> could just run this and mess around with the interface.
> The other possibility is to have a small set of data files that they could
> open.
> 
> On Fri, Sep 4, 2015 at 9:45 AM, Scott notifications@github.com wrote:
> 
> > Merged #6
> > 
> > https://github.com/openradar/AMS-Short-Course-on-Open-Source-Radar-Software/pull/6
> > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/openradar/AMS-Short-Course-on-Open-Source-Radar-Software/pull/6#event-401276220
> > .
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/openradar/AMS-Short-Course-on-Open-Source-Radar-Software/pull/6#issuecomment-137773292.

## 

I ride for Parkinsons research http://www.events.org/sponsorship.aspx?id=51573

**Comment by nguy** [comment]
Sweet!

**Pull request merged**
