### PR TITLE
Added CSU_RadarTools and PyTDA notebooks

### PR DESCRIPTION
**Pull request by tjlang**

### CODE REVIEW

**Comment by jjhelmus** [comment]
Looks good, merging.  Do you know in which order you plan to present these?

**Comment by tjlang** [comment]
CSU_RadarTools, then PyTDA if there is time

**Comment by hzshao** [comment]
Thanks for your last reply.
sorry to bother you again.
How do you covert your radar echo data to the "cfrad.20060119_170029.000_to_20060121_020810.000_CPOL_v1_PPI.nc"  and where  I can get the radar echo data.

**Comment by scollis** [comment]
Hello!
All data is here and free to donwload
http://figshare.com/articles/Data_for_AMS_Short_Course_on_Open_Source_Radar_Software/1537461

This is CF-Radial. Our C-band radar and many other systems use this 
format. You can use RadX to do conversions or Py-ART reads many other 
formats

**Comment by hzshao** [comment]
sorry,that's not my wanted.what I want is a method or tool to handle the original radar echo data and change it to .nc data.Then I will  employ CSU_RadarTools for analysis  with my own data.

**Comment by scollis** [comment]
Please switch to using the Py-ART email list
pyart-users@googlegroups.com pyart-users@googlegroups.com

And let us know what format your radar data is in

**Comment by hzshao** [comment]
Good morning.
I come from China.We do not have dual linear polarization radar data.So my boss said that we should download the echo data from  the NOAA.
my question as follows:
 Question one:  the data download from the NOAA can read by Py-ART?
 Question two: if not,I see your data is end by .nc .How can I convert the data which is downloaded from  the NOAA to the type of your data.
Have a nice day!

**Pull request merged**
