### PR TITLE
ARTview updated.

### PR DESCRIPTION
**Pull request by nguy**
Added a notebook example and goals for ARTview portion.

### CODE REVIEW

**Comment by scollis** [comment]
Great, Thanks @nguy !

**Comment by nguy** [comment]
@scollis I have a data file in there. How are we going to handle that?

**Comment by scollis** [comment]
How big?

On 8/20/15 4:59 PM, Nick wrote:

> @scollis https://github.com/scollis I have a data file in there. How 
> are we going to handle that?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/openradar/AMS-Short-Course-on-Open-Source-Radar-Software/pull/5#issuecomment-133190309.

## 

I ride for Parkinsons research http://www.events.org/sponsorship.aspx?id=51573

**Comment by nguy** [comment]
26MB

**Comment by nguy** [comment]
I assume we will have some sort of community computer or are we switching computers throughout the day?

**Comment by scollis** [comment]
Probably my laptop... We will also have thumbdrives so from now on avoid 
data files.. I will set up a figshare repo

On 8/20/15 5:02 PM, Nick wrote:

> I assume we will have some sort of community computer or are we 
> switching computers throughout the day?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/openradar/AMS-Short-Course-on-Open-Source-Radar-Software/pull/5#issuecomment-133191452.

## 

I ride for Parkinsons research http://www.events.org/sponsorship.aspx?id=51573

**Comment by jjhelmus** [comment]
I could host it in [GitHub Large File Storage](https://git-lfs.github.com/?utm_source=github_site&utm_medium=blog&utm_campaign=gitlfs) but I think I would burn through my 1 GB of bandwidth per month pretty quickly.

**Comment by nguy** [comment]
Okay, it should be fine. The other option is to make this a static presentation and just show the figures, text. But a launching window is always nice!

Whatever the best solution, you let me know.

**Pull request merged**
